# Generated by Django 5.0.6 on 2024-07-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GcomApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='Offre',
            new_name='description',
        ),
    ]
