# Generated by Django 5.0.6 on 2024-07-08 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GcomApp', '0004_alter_command_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
