# Generated by Django 5.0.6 on 2024-07-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GcomApp', '0005_alter_command_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
