# Generated by Django 5.0.6 on 2024-07-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GcomApp', '0006_remove_client_status_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.ManyToManyField(related_name='clients', to='GcomApp.status'),
        ),
    ]
