# Generated by Django 5.0.6 on 2024-07-09 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GcomApp', '0007_status_client_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GcomApp.command')),
            ],
        ),
    ]
