# Generated by Django 5.0.6 on 2024-07-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GcomApp', '0008_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='commande',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='commande',
            field=models.ManyToManyField(to='GcomApp.command'),
        ),
    ]
