# Generated by Django 5.0.6 on 2024-07-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GcomApp', '0009_remove_fournisseur_commande_fournisseur_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='type_commande',
            field=models.CharField(choices=[('Prestation', 'Prestation'), ('Materiel', 'Materiel'), ('Materiel et Prestation', 'Materiel et Prestation')], default='Prestation', max_length=30),
        ),
    ]
