# Generated by Django 5.0.6 on 2024-07-14 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GcomApp', '0010_alter_command_type_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='command',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='CommandeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GcomApp.command')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GcomApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='products',
            field=models.ManyToManyField(related_name='commands', through='GcomApp.CommandeProduct', to='GcomApp.product'),
        ),
        migrations.CreateModel(
            name='CommandeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GcomApp.command')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GcomApp.service')),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='services',
            field=models.ManyToManyField(related_name='commands', through='GcomApp.CommandeService', to='GcomApp.service'),
        ),
    ]
