# Generated by Django 5.0.6 on 2024-07-14 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GcomApp', '0011_product_service_alter_command_date_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='commande',
        ),
    ]
