# Generated by Django 5.0.7 on 2024-07-22 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GcomApp', '0012_remove_command_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='command',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='GcomApp.command'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offre',
            name='profit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
