# Generated by Django 5.0.7 on 2024-07-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GcomApp', '0013_offre_command_offre_profit_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='description',
        ),
    ]
