# Generated by Django 5.0.7 on 2024-07-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GcomApp', '0014_remove_offre_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='client',
        ),
    ]
