# Generated by Django 4.2.13 on 2024-09-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GcomApp', '0017_client_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='adresse',
        ),
    ]
